// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReportBuilder.Infrastructure.DataAccess;

#nullable disable

namespace ReportBuilder.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(ConfigApplicationDbContext))]
    [Migration("20241010160740_fields-table-datatype")]
    partial class fieldstabledatatype
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReportBuilder.Domain.Schema.Fields.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldAlias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Fields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "richard",
                            CreatedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1475),
                            DataType = "string",
                            FieldAlias = "Key",
                            FieldName = "key",
                            LastModifiedBy = "richard",
                            LastModifiedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1523)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "richard",
                            CreatedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1526),
                            DataType = "string",
                            FieldAlias = "Summary",
                            FieldName = "summary",
                            LastModifiedBy = "richard",
                            LastModifiedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1527)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "richard",
                            CreatedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1529),
                            DataType = "object",
                            FieldAlias = "Issue Type",
                            FieldName = "issuetype",
                            LastModifiedBy = "richard",
                            LastModifiedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1530)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "richard",
                            CreatedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1531),
                            DataType = "object",
                            FieldAlias = "Parent",
                            FieldName = "parent",
                            LastModifiedBy = "richard",
                            LastModifiedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1532)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "richard",
                            CreatedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1533),
                            DataType = "object",
                            FieldAlias = "Status",
                            FieldName = "status",
                            LastModifiedBy = "richard",
                            LastModifiedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1534)
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "richard",
                            CreatedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1536),
                            DataType = "object",
                            FieldAlias = "Priority",
                            FieldName = "priority",
                            LastModifiedBy = "richard",
                            LastModifiedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1537)
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "richard",
                            CreatedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1538),
                            DataType = "datetime",
                            FieldAlias = "Due Date",
                            FieldName = "duedate",
                            LastModifiedBy = "richard",
                            LastModifiedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1539)
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "richard",
                            CreatedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1540),
                            DataType = "list<object>",
                            FieldAlias = "Sprints",
                            FieldName = "customfield_10020",
                            LastModifiedBy = "richard",
                            LastModifiedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1541)
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "richard",
                            CreatedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1542),
                            DataType = "list<object>",
                            FieldAlias = "Issue Links",
                            FieldName = "issuelinks",
                            LastModifiedBy = "richard",
                            LastModifiedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1543)
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "richard",
                            CreatedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1545),
                            DataType = "object",
                            FieldAlias = "Assigned To",
                            FieldName = "assignee",
                            LastModifiedBy = "richard",
                            LastModifiedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1546)
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "richard",
                            CreatedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1547),
                            DataType = "list<object>",
                            FieldAlias = "History",
                            FieldName = "changelog",
                            LastModifiedBy = "richard",
                            LastModifiedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1548)
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "richard",
                            CreatedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1549),
                            DataType = "list<object>",
                            FieldAlias = "Components",
                            FieldName = "components",
                            LastModifiedBy = "richard",
                            LastModifiedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1550)
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "richard",
                            CreatedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1551),
                            DataType = "number",
                            FieldAlias = "Story Points",
                            FieldName = "customfield_10038",
                            LastModifiedBy = "richard",
                            LastModifiedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1552)
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = "richard",
                            CreatedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1553),
                            DataType = "string",
                            FieldAlias = "Team",
                            FieldName = "customfield_10001",
                            LastModifiedBy = "richard",
                            LastModifiedDate = new DateTime(2024, 10, 10, 17, 7, 39, 924, DateTimeKind.Local).AddTicks(1554)
                        });
                });

            modelBuilder.Entity("ReportBuilder.Domain.Schema.ReportBuilder.ReportDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExpandChangeLog")
                        .HasColumnType("bit");

                    b.Property<string>("Fields")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JqlQuery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReportDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
